/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GestorCampania;
import Modelo.Campania;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    GestorCampania gc = new GestorCampania();

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaImportantNews = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmCampaigns = new javax.swing.JMenu();
        miNewCampaign = new javax.swing.JMenuItem();
        miCloseCampaign = new javax.swing.JMenuItem();
        jmFileClients = new javax.swing.JMenu();
        miNewClient = new javax.swing.JMenuItem();
        miClientConsult = new javax.swing.JMenuItem();
        jmFileProducts = new javax.swing.JMenu();
        miNewProduct = new javax.swing.JMenuItem();
        jmFileOrders = new javax.swing.JMenu();
        miNewOrder = new javax.swing.JMenuItem();
        miRemoveOrder = new javax.swing.JMenuItem();
        miPrintOrder = new javax.swing.JMenuItem();
        jmFilePayments = new javax.swing.JMenu();
        miNewPayment = new javax.swing.JMenuItem();
        jmFilePrizes = new javax.swing.JMenu();
        miNewPrize = new javax.swing.JMenuItem();
        miModifyPrize = new javax.swing.JMenuItem();
        miPrizeStatus = new javax.swing.JMenuItem();
        jmReports = new javax.swing.JMenu();
        jmRepClients = new javax.swing.JMenuItem();
        jmRepProducts = new javax.swing.JMenuItem();
        miRepOrders = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        jmAbout = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 641));
        setMinimumSize(new java.awt.Dimension(1280, 641));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Avisos Importantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1115, 170));
        jPanel1.setPreferredSize(new java.awt.Dimension(1115, 170));

        txtaImportantNews.setEditable(false);
        txtaImportantNews.setBackground(new java.awt.Color(255, 204, 255));
        txtaImportantNews.setColumns(20);
        txtaImportantNews.setRows(5);
        txtaImportantNews.setMinimumSize(new java.awt.Dimension(1350, 22));
        txtaImportantNews.setPreferredSize(new java.awt.Dimension(1350, 94));
        jScrollPane1.setViewportView(txtaImportantNews);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 400, 1240, 180);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondox.net_unas-rojas-y-petalos-de-rosas_1366x768.jpg"))); // NOI18N
        lblBackground.setMinimumSize(new java.awt.Dimension(1280, 620));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-10, -20, 1280, 620);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 4));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(208, 30));

        jmFile.setText("Archivo");

        jmCampaigns.setText("Campañas");

        miNewCampaign.setText("Nueva");
        miNewCampaign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewCampaignActionPerformed(evt);
            }
        });
        jmCampaigns.add(miNewCampaign);

        miCloseCampaign.setText("Cerrar");
        jmCampaigns.add(miCloseCampaign);

        jmFile.add(jmCampaigns);

        jmFileClients.setText("Clientes");

        miNewClient.setText("Nuevo");
        miNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewClientActionPerformed(evt);
            }
        });
        jmFileClients.add(miNewClient);

        miClientConsult.setText("Consultar");
        miClientConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientConsultActionPerformed(evt);
            }
        });
        jmFileClients.add(miClientConsult);

        jmFile.add(jmFileClients);

        jmFileProducts.setText("Productos");

        miNewProduct.setText("Nuevo");
        miNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewProductActionPerformed(evt);
            }
        });
        jmFileProducts.add(miNewProduct);

        jmFile.add(jmFileProducts);

        jmFileOrders.setText("Pedidos");

        miNewOrder.setText("Nuevo");
        miNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewOrderActionPerformed(evt);
            }
        });
        jmFileOrders.add(miNewOrder);

        miRemoveOrder.setText("Eliminar");
        jmFileOrders.add(miRemoveOrder);

        miPrintOrder.setText("Imprimir detalle");
        miPrintOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrintOrderActionPerformed(evt);
            }
        });
        jmFileOrders.add(miPrintOrder);

        jmFile.add(jmFileOrders);

        jmFilePayments.setText("Cobros");

        miNewPayment.setText("Nuevo");
        miNewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewPaymentActionPerformed(evt);
            }
        });
        jmFilePayments.add(miNewPayment);

        jmFile.add(jmFilePayments);

        jmFilePrizes.setText("Premios");

        miNewPrize.setText("Nuevo");
        miNewPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewPrizeActionPerformed(evt);
            }
        });
        jmFilePrizes.add(miNewPrize);

        miModifyPrize.setText("Modificar");
        miModifyPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModifyPrizeActionPerformed(evt);
            }
        });
        jmFilePrizes.add(miModifyPrize);

        miPrizeStatus.setText("Consultar Estado");
        miPrizeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrizeStatusActionPerformed(evt);
            }
        });
        jmFilePrizes.add(miPrizeStatus);

        jmFile.add(jmFilePrizes);

        jMenuBar1.add(jmFile);

        jmReports.setText("Reportes");

        jmRepClients.setText("Clientes");
        jmReports.add(jmRepClients);

        jmRepProducts.setText("Productos");
        jmReports.add(jmRepProducts);

        miRepOrders.setText("Pedidos");
        jmReports.add(miRepOrders);

        jMenuBar1.add(jmReports);

        jmHelp.setText("Ayuda");
        jMenuBar1.add(jmHelp);

        jmAbout.setText("Acerca de");
        jMenuBar1.add(jmAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miClientConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientConsultActionPerformed
        try {
            // TODO add your handling code here:
            ConsultaCliente cc = new ConsultaCliente();
            cc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miClientConsultActionPerformed

    private void miNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewClientActionPerformed
        try {
            // TODO add your handling code here:
            AltaCliente ac = new AltaCliente();
            ac.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewClientActionPerformed

    private void miModifyPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModifyPrizeActionPerformed
        try {
            // TODO add your handling code here:
            ModificarPremio mp = new ModificarPremio();
            mp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miModifyPrizeActionPerformed

    private void miNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewProductActionPerformed
        try {
            // TODO add your handling code here:
            AltaProducto ap = new AltaProducto();
            ap.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewProductActionPerformed

    private void miNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewOrderActionPerformed
        try {
            // TODO add your handling code here:
            AltaPedido ap = new AltaPedido();
            ap.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewOrderActionPerformed

    private void miPrintOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrintOrderActionPerformed
        try {
            // TODO add your handling code here:
            ConsultaPedidoPorCliente cppc = new ConsultaPedidoPorCliente();
            cppc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miPrintOrderActionPerformed

    private void miNewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewPaymentActionPerformed
        try {
            // TODO add your handling code here:
            AltaCobro ac = new AltaCobro();
            ac.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewPaymentActionPerformed

    private void miNewPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewPrizeActionPerformed
        try {
            // TODO add your handling code here:
            AltaPremio ap = new AltaPremio();
            ap.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewPrizeActionPerformed

    private void miPrizeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrizeStatusActionPerformed
        try {
            // TODO add your handling code here:
            ConsultaEstadoPremio cp = new ConsultaEstadoPremio();
            cp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miPrizeStatusActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            ArrayList<Campania> campaigns = new ArrayList<>();
            campaigns = gc.getCampaingSoonToClose();
            String message = "";
            String message2 = "";
            for (Campania campaign : campaigns) {
                message += "La Campaña " + campaign.getDescription() + " está por cerrar! Fecha de cierre: "+ campaign.getCloseDate() +" \n";
            }
            ArrayList<Campania> campaignsArrival = new ArrayList<>();
            campaignsArrival = gc.getCampaingSoonArrival();
            for (Campania campania : campaignsArrival) {
                message2 += "El pedido de la Campaña " + campania.getDescription() + " está por llegar! Fecha de Arribo: " + campania.getArrivalDate() + " \n\n";
            }
            txtaImportantNews.setText(message + "\n" + message2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void miNewCampaignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewCampaignActionPerformed
        try {
            // TODO add your handling code here:
            AltaCampania ac = new AltaCampania();
            ac.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miNewCampaignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JMenu jmCampaigns;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmFileClients;
    private javax.swing.JMenu jmFileOrders;
    private javax.swing.JMenu jmFilePayments;
    private javax.swing.JMenu jmFilePrizes;
    private javax.swing.JMenu jmFileProducts;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenuItem jmRepClients;
    private javax.swing.JMenuItem jmRepProducts;
    private javax.swing.JMenu jmReports;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenuItem miClientConsult;
    private javax.swing.JMenuItem miCloseCampaign;
    private javax.swing.JMenuItem miModifyPrize;
    private javax.swing.JMenuItem miNewCampaign;
    private javax.swing.JMenuItem miNewClient;
    private javax.swing.JMenuItem miNewOrder;
    private javax.swing.JMenuItem miNewPayment;
    private javax.swing.JMenuItem miNewPrize;
    private javax.swing.JMenuItem miNewProduct;
    private javax.swing.JMenuItem miPrintOrder;
    private javax.swing.JMenuItem miPrizeStatus;
    private javax.swing.JMenuItem miRemoveOrder;
    private javax.swing.JMenuItem miRepOrders;
    private javax.swing.JTextArea txtaImportantNews;
    // End of variables declaration//GEN-END:variables

}
